iz7:-
    write("Какая категория вашего автомобиля?"), nl,
    write("1. A"), nl,
    write("2. B"), nl,
    write("3. C"), nl,
    write("4. D"), nl,
    read(Category), nl,

    write("Ваш автомобиль выпускается на данный момент?"), nl,
    write("1. Да"), nl,
    write("2. Нет"), nl,
    read(IsAliveNow), nl,

    write("Какой тип кузова у вашего автомобиля?"), nl,
    write("1. Седан"), nl,
    write("2. Хэтчбек"), nl,
    write("3. Универсал"), nl,
    write("4. Внедорожник"), nl,
    write("5. Иной"), nl,
    read(BodyType), nl,

    write("К какому региону принадлежит марка вашего автомобиля?"), nl,
    write("1. Азия"), nl,
    write("2. Европа"), nl,
    write("3. Америка"), nl,
    write("4. Иной"), nl,
    read(RegionOfProduction), nl,

    write("Каково расположение ведущих колёс?"), nl,
    write("1. Заднеприводная компоновка"), nl,
    write("2. Переднеприводная компоновка"), nl,
    write("3. Полноприводная компоновка"), nl,
    write("4. Иной"), nl,
    read(Composition), nl,

    write("Какой вид мотора у вашей машины?"), nl,
    write("1. Бензин / дизель"), nl,
    write("2. Электричество"), nl,
    write("3. Гибрид"), nl,
    read(MotorType), nl,
